//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YugiohApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carta()
        {
            this.Deck = new HashSet<Deck>();
        }
    
        public int IdCarta { get; set; }
        public string NomeCarta { get; set; }
        public Nullable<int> Nivel { get; set; }
        public string NumeroCarta { get; set; }
        public Nullable<int> Ataque { get; set; }
        public Nullable<int> Defesa { get; set; }
        public string DescricaoCarta { get; set; }
        public Nullable<int> TipoCartaId { get; set; }
        public Nullable<int> AtributoId { get; set; }
        public Nullable<int> IconeId { get; set; }
    
        public virtual Atributo Atributo { get; set; }
        public virtual Icone Icone { get; set; }
        public virtual TipoCarta TipoCarta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deck> Deck { get; set; }
    }
}
