//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YugiohApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magia
    {
        public int IdMagia { get; set; }
        public string NomeMagia { get; set; }
        public Nullable<int> TipoCartaId { get; set; }
    
        public virtual TipoCarta TipoCarta { get; set; }
    }
}
