//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YugiohApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonstroEfeito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonstroEfeito()
        {
            this.MonstroPenduloes = new HashSet<MonstroPendulo>();
        }
    
        public int IdMonstroEfeito { get; set; }
        public string NomeMonstroEfeito { get; set; }
        public Nullable<int> MonstroId { get; set; }
    
        public virtual Monstro Monstro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonstroPendulo> MonstroPenduloes { get; set; }
    }
}
