//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YugiohApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class userDBEntities1 : DbContext
    {
        public userDBEntities1()
            : base("name=userDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Atributo> Atributo { get; set; }
        public virtual DbSet<Carta> Carta { get; set; }
        public virtual DbSet<Deck> Deck { get; set; }
        public virtual DbSet<Icone> Icone { get; set; }
        public virtual DbSet<LogAcesso> LogAcesso { get; set; }
        public virtual DbSet<TipoCarta> TipoCarta { get; set; }
        public virtual DbSet<TipoDeck> TipoDeck { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Armadilha> Armadilha { get; set; }
        public virtual DbSet<Magia> Magia { get; set; }
        public virtual DbSet<Monstro> Monstro { get; set; }
        public virtual DbSet<MonstroEfeito> MonstroEfeito { get; set; }
        public virtual DbSet<MonstroPendulo> MonstroPendulo { get; set; }
    }
}
